dnaphe/dnaphe/dnaphe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

dnaphe/dnaphe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

dnaphe/dnaphe/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.shortcuts import redirect
import datetime

# Create your models here.
class Topic(models.Model):
    topic_text = models.CharField(max_length=200)

    def __str__(self):
        return self.topic_text
		
    class Meta:
        ordering = ['topic_text']

class Lang_tag(models.Model):
    lang_tag_text = models.CharField(max_length=200)

    def __str__(self):
        return self.lang_tag_text

class Post(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    language = models.ForeignKey(Lang_tag, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=250)
    content = models.TextField()
    upvote = models.IntegerField(default=0, blank=True, null=True)
    downvote = models.IntegerField(default=0, blank=True, null=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    url = models.CharField(max_length=500, null=True, blank=True)
    img_url = models.CharField(max_length=500, null=True, blank=True)
    video_url = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('index')

    def was_published_recently(self):
        return self.date_posted >= timezone.now() - datetime.timedelta(days=5)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    comment_text = models.TextField()
    comment_upvote = models.IntegerField(default=0)
    comment_downvote = models.IntegerField(default=0)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment_text

    def get_absolute_url(self):
        return ('/post/%s'  %self.post.id)


class T_Jobs(models.Model):
    job_name = models.CharField(max_length=25)
    job_desc = models.TextField()
    trigger = models.IntegerField(default=0)
    job_status = models.IntegerField(default=0)
    job_msg = models.TextField(blank=True)
    dte_last_update = models.DateTimeField(default=timezone.now)
    #job_name, job_desc, trigger, trigger_desc, job_status, job_msg

    def __str__(self):
        return self.job_name

dnaphe/dnaphe/users/models.py
from django.db import models

# Create your models here.

dnaphe/dnaphe/home/forms.py
from django import forms
from pagedown.widgets import PagedownWidget

from .models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment_text',)


class LinkPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('topic', 'language', 'title', 'url')


class TextPostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget)

    class Meta:
        model = Post
        fields = ['topic', 'language', 'title', 'content']


class PostUpdateForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget)

    class Meta:
        model = Post
        fields = ['topic', 'language', 'title',  'content', 'url']

dnaphe/dnaphe/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
# from .models import Profile


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

dnaphe/dnaphe/home/templates/home/add_comment_to_post.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="w3-button btn btn-default">Send</button>
    </form>
{% endblock %}

dnaphe/dnaphe/home/templates/home/bot_content.html
<title>bot content</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css'
          integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>

{% extends 'home/bot_page.html' %}
{% block botcontent %}
<br><br>
{% for post in posts %}

<div clas="w3-card-4 w3-border">
    <div class="card-header">
        <p>on <b>news</b> by onlineKhabarBot</p>

    </div>
    <div class="container">
        <h3>title: {{ post.0 }} </h3>
        <div class="row">
            <div class="w3-container w3-half">
                <a href="{{ post.2 }}" target="_blank">content: {{ post.1 }} </a>
            </div>
            <div class="w3-container w3-half">
                <img src="{{post.3}}">
            </div>
        </div>


    </div>
</div>
<br>
{% endfor %}
{% endblock %}

dnaphe/dnaphe/home/templates/home/canada_nepal_bot_content.html
<title>bot content</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css'
          integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>

{% extends 'home/bot_page.html' %}
{% block botcontent %}
<br><br>
{% for post in posts %}

<div clas="w3-card-4 w3-border">
    <div class="card-header w3-containet">
        <p>on <b>news</b> by onlineKhabarBot</p>

    </div>
    <div class="w3-container">
        <h3>title: {{ post.0 }} </h3>
        <div class="row">
            <div class="w3-container w3-half">
                <a href="{{ post.2 }}" target="_blank">content: {{ post.1 }} </a>
            </div>
            <div class="col">
                    <iframe width="100%" src="{{post.3}}" frameborder="0"
                            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
                    </iframe>
            </div>
        </div>


    </div>
</div>
<br>
{% endfor %}
{% endblock %}

dnaphe/dnaphe/home/templates/home/comment_confirm_delete.html
{% extends "home/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom-mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the following comment</h2>
                <h4>"{{ object.comment_text }}"</h4>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

dnaphe/dnaphe/home/templates/home/post_confirm_delete.html
{% extends "home/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom-mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the following post</h2>
                <h4>"{{ object.title }}"</h4>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

dnaphe/dnaphe/home/templates/home/post_detail_o.html
<title>dnaphe</title>
{% extends "home/base.html" %}
{% load humanize %}
{% block content %}
{% for post in posts %}
<div name="post_placeholder" id="paceholder_{{post.id}}">
<div class="w3-card-4 w3-white w3-round" id="{{ post.id }}">
    <header class="w3-container card-header w3-small text-muted" style="margin-bottom: 0;">
        <p style="margin-bottom: 0;">on
            <b>
                <a href="{% url 'topics-home' post.topic.id %}">{{post.topic}}</a>
            </b> by
            <b>
                <a href="{% url 'user-profile' post.author %}">{{post.author}}</a>
            </b>
        <span class="w3-right" style="margin-bottom: 0;">{{post.date_posted|naturaltime}}</span>
      </p>
    </header>
<!--      <hr class="beautify">-->

    <div class="w3-container">
        <h3>{{post.title}}</h3>
      <div class="row">

                <div class="col">
				
				{% if post.url %}
                    <a href="{{ post.url }}" target="_blank" style="text-decoration: none">{{ post.content }} </a>
				{% else %}		   
					<p>{{post.content}}</p>								   
				{% endif %}	  
                </div>
				
				{% if post.video_url and post.img_url%}
				<div class="col">
                    <iframe width="100%" src="{{post.video_url}}" frameborder="0" allow="gyroscope; encrypted-media; picture-in-picture" allowfullscreen></iframe>
                </div>
                {% elif post.img_url %}
                <div class="col">
                    <a href="{{ post.url }}" target="_blank" style="text-decoration: none">
                        <div class="w3-card w3-hover-shadow">
                            <img src="{{post.img_url}}" style="width: 100%">
                        </div>
                    </a>
                </div>
                {% endif %}

        </div>
    </div>
    <hr class="beautify">

      <footer class="w3-container w3-small text-muted" style="margin-bottom: 0;">
        <p style="margin-bottom: 0;">
            {% if user.is_authenticated %}
            <a href="{% url 'upvote' post.id %}" name="post_upvote" style="text-decoration: none">
                <i class='fas fa-long-arrow-alt-up'></i>
            </a>
            {% else %}
            <button data-toggle="modal" class="w3-white" style="border: none;" data-target="#signInModal" name="post_upvote" style="text-decoration: none">
                <i class='fas fa-long-arrow-alt-up'></i>
            </button>
            {% endif %}
            {% if post.upvote != 0 %}
                    {{post.upvote}}
            {% endif %}

            {% if user.is_authenticated %}
            <a href="{% url 'downvote' post.id %}" name="post_downvote" style="text-decoration: none">
                        <i class='fas fa-long-arrow-alt-down'></i>
            </a>
            {% else %}
            <button data-toggle="modal" class="w3-white" style="border: none;" data-target="#signInModal" name="post_upvote" style="text-decoration: none">
                <i class='fas fa-long-arrow-alt-down'></i>
            </button>
            {% endif %}

            {% if post.downvote != 0 %}
                    {{post.downvote}}
            {% endif %}
            {% if post.author == user or user.is_staff %}

                <a href="{% url 'post-update' post.id %}" style="text-decoration: none">update</a>
                <a href="{% url 'post-delete' post.id %}" style="text-decoration: none">delete</a>

            {% endif %}
            <span class="w3-right" style="margin-bottom: 0; margin-top: 3px;">
<!--                <a href="#commentModal" name="post_downvote" style="text-decoration: none">-->
<!--                    <i class='fas fa-reply'></i>-->
<!--                </a>-->
                {% if user.is_authenticated %}
                <button type="button" data-toggle="modal" class="w3-white" style="border: none;" data-target="#postcommentModal">{{post.comments.count}}
                    <i class='fas fa-reply'></i>
                </button>
                {% else %}
                <button type="button" data-toggle="modal" class="w3-white" style="border: none;" data-target="#signInModal">{{post.comments.count}}
                    <i class='fas fa-reply'></i>
                </button>
                {% endif %}
            </span>
        </p>
      </footer>

  </div><br>
<div class="modal fade" id="postcommentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h6 class="modal-title" id="commentModalLabel">Create a comment</h6>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        <form method="POST" class="post-form" action="{% url 'add_comment_to_post' post.id %}">
            {% csrf_token %}
                <p>
                    <label for="id_comment_text">Comment text:</label>
<!--                    <input type="text" name="comment_text" maxlength="1000" required="" id="id_comment_text">-->
                    <textarea name="comment_text" style="width: 100%" rows="10" required="" id="id_comment_text"></textarea>
                </p>
                <button type="submit" class="btn btn-primary">Send</button>
        </form>
        </div>
      </div>
    </div>
</div>
</div>
{% endfor %}


{% for comment in comments %}
<div name="comment_placeholder" id="paceholder_{{comment.id}}">
<div class="w3-card-4 w3-white w3-round">
    <header class="w3-container card-header w3-small text-muted" style="margin-bottom: 0;">
        <p style="margin-bottom: 0;">by
            <b>
                <a href="{% url 'user-profile' comment.author %}">{{comment.author}}</a>
            </b>
            <span class="w3-right" style="margin-bottom: 0;">{{comment.date_posted|naturaltime}}</span>
        </p>
    </header>

    <div class="w3-container w3-margin-top">
        <p>{{comment.comment_text}}</p>
    </div>
    <hr class="beautify">

    <footer class="w3-container w3-small text-muted" style="margin-bottom: 0;">
        <p style="margin-bottom: 0;">
            <a href="{% url 'comment_upvote' comment.id %}" name="comment_upvote" style="text-decoration: none">
                <i class='fas fa-long-arrow-alt-up'></i>
            </a>
            {% if comment.comment_upvote != 0 %}
                    {{comment.comment_upvote}}
            {% endif %}
            <a href="{% url 'comment_downvote' comment.id %}" name="comment_downvote" style="text-decoration: none">
                        <i class='fas fa-long-arrow-alt-down'></i>
            </a>
            {% if comment.comment_downvote != 0 %}
                    {{comment.comment_downvote}}
            {% endif %}

            {% if post.author == user or user.is_staff %}

                <a href="{% url 'comment-update' post_id=comment.post.id pk=comment.id %}" style="text-decoration: none">update</a>
                <a href="{% url 'comment-delete' post_id=comment.post.id pk=comment.id %}" style="text-decoration: none">delete</a>

            {% endif %}

            <span class="w3-right" style="margin-bottom: 0; margin-top: 3px;">
                {% if user.is_authenticated %}
                <button type="button" data-toggle="modal" class="w3-white" style="border: none;" data-target="#commentcommentModal">
                    <i class='fas fa-reply'></i>
                </button>
                {% else %}
                <button type="button" data-toggle="modal" class="w3-white" style="border: none;" data-target="#signInModal">
                    <i class='fas fa-reply'></i>
                </button>
                {% endif %}
            </span>
        </p>

      </footer>
  </div><br>
<div class="modal fade" id="commentcommentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h6 class="modal-title" id="commentModalLabel">Create a comment</h6>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        <form method="POST" class="post-form" action="{% url 'add_comment_to_post' comment.post.id %}">
            {% csrf_token %}
                <p>
                    <label for="id_comment_text">Comment text:</label>
                    <textarea name="comment_text" style="width: 100%" rows="10" required="" id="id_comment_text"></textarea>
                </p>
                <button type="submit" class="btn btn-primary">Send</button>
        </form>
        </div>
      </div>
    </div>
</div>
</div>
{% endfor %}

<!--************modals for comment button ******************-->


<div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="signInModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="postModalLabel">Please log in to continue!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          {% load crispy_forms_tags %}
        <div class="content-section">
        <form method="POST" action="/login/">
            {% csrf_token %}
            <fieldset class="form-group">
<!--                <legend class="border-bottom-mb-4">Log In</legend>-->
                <div id="div_id_username" class="form-group">
                    <label for="id_username" class="col-form-label  requiredField">Username<span class="asteriskField">*</span>
                    </label>
                    <div class="">
                        <input type="text" name="username" autofocus class="textinput textInput form-control" required id="id_username">
                    </div>
                </div>
                <div id="div_id_password" class="form-group">
                    <label for="id_password" class="col-form-label  requiredField">Password<span class="asteriskField">*</span>
                    </label>
                    <div class="">
                        <input type="password" name="password" class="textinput textInput form-control" required id="id_password">
                    </div>
                </div>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an Account? <a class="ml-2" href="/register/">Sign Up Now</a>
            </small>
        </div>
    </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

dnaphe/dnaphe/home/templates/home/user_profile.html
{% extends 'home/base.html' %}
{% load markdown_deux_tags %}
{% load humanize %}
{% block content %}
<div class="w3-container" id="menu" style="width: 100%">
  <div class="w3-content">
    {% for user in user %}
    <h1 class="w3-center w3-jumbo" style="margin-bottom:35px">{{user.username}}</h1>
    {% endfor %}
    <div class="w3-row w3-center w3-border-bottom w3-border-light-grey">
      <a href="javascript:void(0)" onclick="openMenu(event, 'Profile');" id="myLink">
        <div class="w3-col s4 tablink  w3-hover-light-green"><b>Profile</b></div>
      </a>
      <a href="javascript:void(0)" onclick="openMenu(event, 'Posts');">
        <div class="w3-col s4 tablink  w3-hover-light-green"><b>Posts</b></div>
      </a>
      <a href="javascript:void(0)" onclick="openMenu(event, 'Comments');">
        <div class="w3-col s4 tablink  w3-hover-light-green"><b>Comments</b></div>
      </a>
    </div>

    <div id="Profile" class="w3-container menu w3-padding-32 w3-white">
<!--      <h1><b>Margherita</b> <span class="w3-right w3-tag w3-dark-grey w3-round">$12.50</span></h1>-->
<!--      <p class="w3-text-grey">Fresh tomatoes, fresh mozzarella, fresh basil</p>-->
<!--      <hr>-->
        <p>Total user posts:      {{posts|length}} </p>
        <p>Total user comments:   {{comments|length}}</p>


    </div>

    <div id="Posts" class="w3-container menu w3-padding-32 w3-white">
        {% for post in posts %}
            <div class="w3-card-4 w3-white w3-round" id="{{ post.id }}">
                <header class="w3-container card-header w3-small text-muted" style="margin-bottom: 0;">
                    <p style="margin-bottom: 0;">on
                        <b>
                            <a href="{% url 'topics-home' post.topic.id %}">{{post.topic}}</a>
                        </b> by
                        <b>
                            <a href="{% url 'user-profile' post.author %}">{{post.author}}</a>
                        </b>
                    <span class="w3-right" style="margin-bottom: 0;">{{post.date_posted|naturaltime}}</span>
                  </p>
                </header>
            <!--      <hr class="beautify">-->

                <div class="w3-container">
                    <a href="{% url 'post-detail' post.id %}" style="text-decoration: none"><h4>{{post.title}}</h4></a>
                  <div class="row">

                            <div class="col w3-hide-medium w3-hide-small">
                                <a href="{% url 'post-detail' post.id %}" style="text-decoration: none">{{ post.content|markdown|truncatewords_html:15 }} </a>
                            </div>
                            {% if post.img_url %}
                            <div class="col">
                                <a href="{{ post.url }}" target="_blank" style="text-decoration: none">
                                    <div class="w3-card">
                                        <img src="{{post.img_url}}" style="width: 100%">
                                    </div>
                                </a>
                            </div>
                            {% endif %}

                    </div>
                </div>
                <hr class="beautify">

                  <footer class="w3-container w3-small text-muted" style="margin-bottom: 0;">
                    <p style="margin-bottom: 0;">
                        {% if user.is_authenticated %}
                        <a href="{% url 'upvote' post.id %}" name="post_upvote" style="text-decoration: none">
                            <i class='fas fa-long-arrow-alt-up'></i>
                        </a>
                        {% else %}
                        <button data-toggle="modal" class="w3-white" style="border: none;" data-target="#signInModal" name="post_upvote" style="text-decoration: none">
                            <i class='fas fa-long-arrow-alt-up'></i>
                        </button>
                        {% endif %}
                        {% if post.upvote != 0 %}
                                {{post.upvote}}
                        {% endif %}

                        {% if user.is_authenticated %}
                        <a href="{% url 'downvote' post.id %}" name="post_downvote" style="text-decoration: none">
                                    <i class='fas fa-long-arrow-alt-down'></i>
                        </a>
                        {% else %}
                        <button data-toggle="modal" class="w3-white" style="border: none;" data-target="#signInModal" name="post_upvote" style="text-decoration: none">
                            <i class='fas fa-long-arrow-alt-down'></i>
                        </button>
                        {% endif %}

                        {% if post.downvote != 0 %}
                                {{post.downvote}}
                        {% endif %}
                        <span class="w3-right" style="margin-bottom: 0; margin-top: 3px;">
            <!--                <a href="#commentModal" name="post_downvote" style="text-decoration: none">-->
            <!--                    <i class='fas fa-reply'></i>-->
            <!--                </a>-->
                            {% if user.is_authenticated %}
                            <button type="button" data-toggle="modal" class="w3-white" style="border: none;" data-target="#postcommentModal">
                                <i class='fas fa-reply'></i>
                            </button>
                            {% else %}
                            <button type="button" data-toggle="modal" class="w3-white" style="border: none;" data-target="#signInModal">
                                <i class='fas fa-reply'></i>
                            </button>
                            {% endif %}
                        </span>
                    </p>
                  </footer>

              </div><br>
            <div class="modal fade" id="postcommentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h6 class="modal-title" id="commentModalLabel">Create a comment</h6>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                    <form method="POST" class="post-form" action="{% url 'add_comment_to_post' post.id %}">
                        {% csrf_token %}
                            <p>
                                <label for="id_comment_text">Comment text:</label>
            <!--                    <input type="text" name="comment_text" maxlength="1000" required="" id="id_comment_text">-->
                                <textarea name="comment_text" style="width: 100%" rows="10" required="" id="id_comment_text"></textarea>
                            </p>
                            <button type="submit" class="btn btn-primary">Send</button>
                    </form>
                    </div>
                  </div>
                </div>
            </div>
        {% endfor %}
    </div>


    <div id="Comments" class="w3-container menu w3-padding-32 w3-white">
        {% for comment in comments %}
            <div class="w3-card-4 w3-white w3-round">
    <header class="w3-container card-header w3-small text-muted" style="margin-bottom: 0;">
<!--        <p style="margin-bottom: 0;">by <b>{{comment.author}}</b>-->
<!--      </p>-->
        <p style="margin-bottom: 0;">by
            <b>
                <a href="{% url 'user-profile' comment.author %}">{{comment.author}}</a>
            </b>on post
            <b>
                <a href="{% url 'post-detail' comment.post.id %}" style="text-decoration: none">{{comment.post.title|truncatechars:10}}</a>
            </b>
            <span class="w3-right" style="margin-bottom: 0;">{{comment.date_posted|naturaltime}}</span>
        </p>
    </header>

    <div class="w3-container w3-margin-top">
        <p>{{comment.comment_text}}</p>
    </div>
    <hr class="beautify">

    <footer class="w3-container w3-small text-muted" style="margin-bottom: 0;">
        <p style="margin-bottom: 0;">
            <a href="{% url 'comment_upvote' comment.id %}" name="comment_upvote" style="text-decoration: none">
                <i class='fas fa-long-arrow-alt-up'></i>
            </a>
            {% if comment.comment_upvote != 0 %}
                    {{comment.comment_upvote}}
            {% endif %}
            <a href="{% url 'comment_downvote' comment.id %}" name="comment_downvote" style="text-decoration: none">
                        <i class='fas fa-long-arrow-alt-down'></i>
            </a>
            {% if comment.comment_downvote != 0 %}
                    {{comment.comment_downvote}}
            {% endif %}
            <span class="w3-right" style="margin-bottom: 0; margin-top: 3px;">
                {% if user.is_authenticated %}
                <button type="button" data-toggle="modal" class="w3-white" style="border: none;" data-target="#commentcommentModal">
                    <i class='fas fa-reply'></i>
                </button>
                {% else %}
                <button type="button" data-toggle="modal" class="w3-white" style="border: none;" data-target="#signInModal">
                    <i class='fas fa-reply'></i>
                </button>
                {% endif %}
            </span>
        </p>

      </footer>
  </div><br>
            <div class="modal fade" id="commentcommentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h6 class="modal-title" id="commentModalLabel">Create a comment</h6>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        <form method="POST" class="post-form" action="{% url 'add_comment_to_post' comment.post.id %}">
            {% csrf_token %}
                <p>
                    <label for="id_comment_text">Comment text:</label>
                    <textarea name="comment_text" style="width: 100%" rows="10" required="" id="id_comment_text"></textarea>
                </p>
                <button type="submit" class="btn btn-primary">Send</button>
        </form>
        </div>
      </div>
    </div>
</div>
        {% endfor %}
    </div><br>

  </div>
</div>


<script>
// Tabbed Menu
function openMenu(evt, menuName) {
  var i, x, tablinks;
  x = document.getElementsByClassName("menu");
  for (i = 0; i < x.length; i++) {
     x[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablink");
  for (i = 0; i < x.length; i++) {
     tablinks[i].className = tablinks[i].className.replace(" w3-light-green", "");
  }
  document.getElementById(menuName).style.display = "block";
  evt.currentTarget.firstElementChild.className += " w3-light-green";
}
document.getElementById("myLink").click();
</script>

{% endblock %}

<!--</body>-->
<!--</html>-->